### ISSUE TITLE
PA Review: Photo feature

### ISSUE THREAD

**Issue by brandt2** [brandt2/WilloWisp-Fullstack#3]
- [x] Logged in users can upload photos
- [x] Users can view a list of photos
- [x] Logged in users can edit existing photos
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by ryan-mapa** [comment]
- [x] add cancel button or allow user to click out of photo edit form.
- [x] fix photo images showing in header on scroll in index view
